feat(ISV-6032): add script to summarize SBOM uploads
Signed-off-by: Martin Jediny <jedinym@proton.me>

diff --git a/scripts/tekton/upload_sboms_to_atlas b/scripts/tekton/upload_sboms_to_atlas
--- a/scripts/tekton/upload_sboms_to_atlas
+++ b/scripts/tekton/upload_sboms_to_atlas
@@ -1,12 +1,14 @@
 #!/usr/bin/env bash
 set -ux
 
-OPTS=$(getopt -o '' --long data-dir:,atlas-api-url:,sbom-path: -- "$@")
+OPTS=$(getopt -o '' --long data-dir:,atlas-api-url:,sbom-path:,report-path:,failed-dir: -- "$@")
 eval set -- "$OPTS"
 
 data_dir=""
 atlas_api_url=""
 sbom_path=""
+failed_dir=""
+report_path=""
 
 while true; do
     case "$1" in
@@ -22,6 +24,14 @@ while true; do
             sbom_path="$2"
             shift 2
             ;;
+        --report-path)
+            report_path="$2"
+            shift 2
+            ;;
+        --failed-dir)
+            failed_dir="$2"
+            shift 2
+            ;;
         --)
             shift
             break
@@ -33,8 +43,13 @@ while true; do
     esac
 done
 
-if [[ -z "$data_dir" || -z "$atlas_api_url" || -z "$sbom_path" ]]; then
-    echo "Error: --data-dir, --atlas-api-url and --sbom-path are required" >&2
+if [[ -z "$data_dir" || \
+      -z "$atlas_api_url" || \
+      -z "$sbom_path" || \
+      -z "$report_path" || \
+      -z "$failed_dir" \
+      ]]; then
+    echo "Error: missing required argument or argument is empty" >&2
     exit 1
 fi
 
@@ -54,9 +69,7 @@ done
 set -x
 
 sbom_path="${data_dir}/${sbom_path}"
-report_path="${data_dir}/report.json"
-failed_path="${data_dir}/failed-sboms"
-mkdir -p "$failed_path"
+mkdir -p "$failed_dir"
 
 if [[ $(find "$sbom_path" -type f | wc -l) -eq 0 ]]; then
     >&2 echo "Error: no SBOMs to upload found."
@@ -77,7 +90,7 @@ if [[ $upload_exit_code -eq 2 ]]; then
   # Then use xargs to copy all the failed SBOM files to a directory, from
   # which the upload-sboms-to-s3 step will push to S3.
   jq '.failure[]' "$report_path" | \
-    xargs -I {} cp {} "$failed_path"
+    xargs -I {} cp {} "$failed_dir"
 elif [[ $upload_exit_code -ne 0 ]]; then
   exit $upload_exit_code
 fi
diff --git a/scripts/tekton/upload_sboms_to_s3 b/scripts/tekton/upload_sboms_to_s3
--- a/scripts/tekton/upload_sboms_to_s3
+++ b/scripts/tekton/upload_sboms_to_s3
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 set -eux
 
-OPTS=$(getopt -o '' --long data-dir:,retry-s3-bucket: -- "$@")
+OPTS=$(getopt -o '' --long data-dir:,retry-s3-bucket:,failed-dir: -- "$@")
 eval set -- "$OPTS"
 
 data_dir=""
 retry_s3_bucket=""
+failed_dir=""
 
 while true; do
     case "$1" in
@@ -15,6 +16,10 @@ while true; do
             ;;
         --retry-s3-bucket)
             retry_s3_bucket="$2"
+            shift 2
+            ;;
+        --failed-dir)
+            failed_dir="$2"
             shift 2
             ;;
         --)
@@ -28,8 +33,11 @@ while true; do
     esac
 done
 
-if [[ -z "$data_dir" || -z "$retry_s3_bucket" ]]; then
-    echo "Error: Both --data-dir and --retry-s3-bucket are required" >&2
+if [[ -z "$data_dir" || \
+      -z "$retry_s3_bucket" || \
+      -z "$failed_dir" \
+      ]]; then
+    echo "Error: missing required argument or is empty" >&2
     exit 1
 fi
 
@@ -47,6 +55,9 @@ for var_name in "${required_vars[@]}"; do
 done
 set -x
 
-failed_path="${data_dir}/failed-sboms"
 
-aws s3 cp "$failed_path" s3://${retry_s3_bucket}/ --recursive
+aws s3 cp "$failed_dir" s3://${retry_s3_bucket}/ --recursive
+
+# remove all uploaded SBOMs, so that a final report can be generated in a
+# further step.
+rm -f "${failed_dir}/*"
